# This gets loaded by `runner.py`
# modelrc and datarc get passed to the model
runner:
  total_steps: 10000
  gradient_clipping: 1
  gradient_accumulate_steps: 8

  log_step: 89  # one epoch
  eval_step: 89
  save_step: 89
  max_keep: 1
  eval_dataloaders:
    - dev
    # - test

optimizer:
  name: AdamW
  lr: 2.e-4
  
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 1000

downstream_expert:
  datarc:
    num_workers: 8
    train_batch_size: 4
    test_batch_size: 4
    dev_batch_size: 4
    data_root: '/home/xt0r3-user/cambridge/partii/dissertation/s3prl/data/l2arctic_release_v5.0'
    phone_path: './downstream/mdd/data'
    # bucket_file: './data/len_for_bucket_timit' # run: `python preprocess/generate_len_for_bucket.py -i your_path_to/TIMIT -a .WAV -n len_for_bucket_timit`
    sample_rate: 44100  # this should not be changed, and this should match the sr of the audio in `data_root`
    train_dev_seed: 1337

  modelrc: 
    none: None